#! /usr/bin/env python
from ROOT import *
from colors import *
colors = defineColors()

lumi = 1.0

######################################################


#dataDir = "/afs/cern.ch/work/z/zdemirag/public/ichep/setup80x/Skim_v2/monojet_"
#dataDir = "eos/cms/store/user/zdemirag/setup80x/Skim_v9/monojet_"


#ichep and postichep
#dataDir = "/afs/cern.ch/work/z/zdemirag/public/ichep/setup80x/Skim_v3/monojet_"

dataDir = "/afs/cern.ch/work/z/zdemirag/public/ichep/setup80x/Skim_v12/monojet_"

physics_processes = {
        'Zll_ht100': { 'label':'Z#rightarrow ll',
                       'datacard':'Zll',
                       'color' : "#9A9EAB", #colors.keys()[4],
                       'ordering': 0,                  
                       'xsec' : 148.0,
                       'files':[dataDir+"DYJetsToLL_M-50_HT-100to200.root"],
                 },
        'Zll_ht200': { 'label':'Z#rightarrow ll',
                       'datacard':'Zll',
                       'color' : "#9A9EAB", #colors.keys()[4],
                       'ordering': 0,                  
                       'xsec' : 40.94,
                       'files':[dataDir+"DYJetsToLL_M-50_HT-200to400.root"],
                       },
        'Zll_ht400': { 'label':'Z#rightarrow ll',
                       'datacard':'Zll',
                       'color' : "#9A9EAB", #colors.keys()[4],
                       'ordering': 0,                  
                       'xsec' : 5.497,
                       'files':[dataDir+"DYJetsToLL_M-50_HT-400to600.root"],
                 },
        'Zll_ht600': { 'label':'Z#rightarrow ll',
                       'datacard':'Zll',
                       'color' : "#9A9EAB", #colors.keys()[4],
                       'ordering': 0,                  
                       'xsec' : 2.193,
                       'files':[dataDir+"DYJetsToLL_M-50_HT-600toInf.root"],
                 },        

        #'Zll_nlo': { 'label':'Z#rightarrow ll',
        #             'datacard':'Zll',
        #             'color' : "#9A9EAB", #colors.keys()[4],
        #             'ordering': 0,                  
        #             'xsec' : 6025.2,
        #             'files':[dataDir+"DYJetsToLL_M-50.root"],
        #             },        

        'Zvv_ht100':{ 'label':'Z#rightarrow#nu#nu', 
                      'datacard':'Zvv', 
                      'color' : "#258039",  #colors.keys()[4], 
                      'ordering': 4,
                      'xsec' : 280.5,
                      'files':[dataDir+"ZJetsToNuNu_HT-100To200_13TeV.root"],
                      },
        'Zvv_ht200':{ 'label':'Z#rightarrow#nu#nu', 
                      'datacard':'Zvv', 
                      'color' : "#258039",  #colors.keys()[1], 
                      'ordering': 4,
                      'xsec' : 77.7,
                      'files':[dataDir+"ZJetsToNuNu_HT-200To400_13TeV.root"],
                      },
        'Zvv_ht400':{ 'label':'Z#rightarrow#nu#nu', 
                      'datacard':'Zvv', 
                      'color' : "#258039",  #colors.keys()[4], 
                      'ordering': 4,
                      'xsec' : 10.71,
                      'files':[dataDir+"ZJetsToNuNu_HT-400To600_13TeV.root"],
                      },
        'Zvv_ht600':{ 'label':'Z#rightarrow#nu#nu', 
                      'datacard':'Zvv', 
                      'color' : "#258039",  #colors.keys()[1], 
                      'ordering': 4,
                      'xsec' : 2.559,
                      'files':[dataDir+"ZJetsToNuNu_HT-600To800_13TeV.root"],
                      },
        'Zvv_ht800':{ 'label':'Z#rightarrow#nu#nu', 
                      'datacard':'Zvv', 
                      'color' : "#258039",  #colors.keys()[1], 
                      'ordering': 4,
                      'xsec' : 0.3942*3,
                      'files':[dataDir+"ZJetsToNuNu_HT-800To1200_13TeV.root"],
                      },
        'Zvv_ht1200':{ 'label':'Z#rightarrow#nu#nu', 
                       'datacard':'Zvv', 
                       'color' : "#258039",  #colors.keys()[1], 
                       'ordering': 4,
                       'xsec' : 0.0974*3,
                       'files':[dataDir+"ZJetsToNuNu_HT-1200To2500_13TeV.root"],
                       },
        'Zvv_ht2500':{ 'label':'Z#rightarrow#nu#nu', 
                       'datacard':'Zvv', 
                       'color' : "#258039",  #colors.keys()[1], 
                       'ordering': 4,
                       'xsec' : 0.002308*3,
                       'files':[dataDir+"ZJetsToNuNu_HT-2500ToInf_13TeV.root"],
                        },
        
        #'Zvv_ht100':{ 'label':'Z#rightarrow#nu#nu', 
        #              'datacard':'Zvv', 
        #              'color' : "#258039",  #colors.keys()[6], 
        #              'ordering': 4,
        #              'xsec' : 55.38*3,
        #              'files':[dataDir+"DYJetsToNuNu_PtZ-100To250.root"],
        #              },
        #'Zvv_ht250':{ 'label':'Z#rightarrow#nu#nu', 
        #              'datacard':'Zvv', 
        #              'color' : "#258039",  #colors.keys()[6], 
        #              'ordering': 4,
        #              'xsec' : 2.060*3,
        #              'files':[dataDir+"DYJetsToNuNu_PtZ-250To400.root"],
        #              },
        #'Zvv_ht400':{ 'label':'Z#rightarrow#nu#nu', 
        #              'datacard':'Zvv', 
        #              'color' :"#258039",  # colors.keys()[6], 
        #              'ordering': 4,
        #              'xsec' : 0.2809*3,
        #              'files':[dataDir+"DYJetsToNuNu_PtZ-400To650.root"],
        #              },
        #'Zvv_ht650':{ 'label':'Z#rightarrow#nu#nu', 
        #              'datacard':'Zvv', 
        #              'color' : "#258039",  #colors.keys()[6], 
        #              'ordering': 4,
        #              'xsec' : 0.0261*3,
        #              'files':[dataDir+"DYJetsToNuNu_PtZ-650ToInf.root"],
        #              },

         'Wlv_ht100': { 'label':'W#rightarrow  l#nu',
                        'datacard':'Wlv',
                        'color' : "#FAAF08", #colors.keys()[2],
                        'ordering': 3,                  
                        'xsec' : 1343.,
                        'files':[dataDir+'WJetsToLNu_HT-100To200.root',],
                        },
         'Wlv_ht200': { 'label':'W#rightarrow  l#nu',
                       'datacard':'Wlv',
                        'color' : "#FAAF08", #colors.keys()[2],
                        'ordering': 3,                  
                        'xsec' : 359.6,
                       'files':[dataDir+'WJetsToLNu_HT-200To400.root',],
                       },
        'Wlv_ht400': { 'label':'W#rightarrow  l#nu',
                        'datacard':'Wlv',
                        'color' : "#FAAF08", #colors.keys()[2],
                        'ordering': 3,                  
                        'xsec' : 48.85,
                        'files':[dataDir+'WJetsToLNu_HT-400To600.root',],
                        },
         'Wlv_ht600': { 'label':'W#rightarrow  l#nu',
                        'datacard':'Wlv',
                        'color' : "#FAAF08", #colors.keys()[2],
                        'ordering': 3,
                        'xsec' : 12.05,
                        'files':[dataDir+'WJetsToLNu_HT-600To800.root',],
                        },
         'Wlv_ht800': { 'label':'W#rightarrow  l#nu',
                        'datacard':'Wlv',
                        'color' : "#FAAF08", #colors.keys()[2],
                        'ordering': 3,
                        'xsec' : 5.5,
                        'files':[dataDir+'WJetsToLNu_HT-800To1200.root',],
                        },
         'Wlv_ht1200': { 'label':'W#rightarrow  l#nu',
                        'datacard':'Wlv',
                        'color' : "#FAAF08", #colors.keys()[2],
                        'ordering': 3,
                        'xsec' : 1.32,
                        'files':[dataDir+'WJetsToLNu_HT-1200To2500.root',],
                        },
         'Wlv_ht2500': { 'label':'W#rightarrow  l#nu',
                        'datacard':'Wlv',
                        'color' : "#FAAF08", #colors.keys()[2],
                        'ordering': 3,
                        'xsec' : 0.032,
                        'files':[dataDir+'WJetsToLNu_HT-2500ToInf.root',],
                        },
        
        #'Wlv_ht100': { 'label':'W#rightarrow  l#nu',
        #               'datacard':'Wlv',
        #               'color' : "#FAAF08", #colors.keys()[5],
        #               'ordering': 3,                  
        #               'xsec' : 682.2,
        #               'files':[dataDir+'WJetsToLNu_Pt-100To250.root',],
        #               },
        #'Wlv_ht250': { 'label':'W#rightarrow  l#nu',
        #               'datacard':'Wlv',
        #               'color' : "#FAAF08", #colors.keys()[5],
        #               'ordering': 3,                  
        #               'xsec' : 24.10,
        #               'files':[dataDir+'WJetsToLNu_Pt-250To400.root',],
        #               },
        #'Wlv_ht400': { 'label':'W#rightarrow  l#nu',
        #               'datacard':'Wlv',
        #               'color' : "#FAAF08", #colors.keys()[5],
        #               'ordering': 3,                  
        #               'xsec' : 3.054,
        #               'files':[dataDir+'WJetsToLNu_Pt-400To600.root',],
        #               },
        #'Wlv_ht600': { 'label':'W#rightarrow  l#nu',
        #               'datacard':'Wlv',
        #               'color' : "#FAAF08", #colors.keys()[5],
        #               'ordering': 3,
        #               'xsec' : 0.4590,
        #               'files':[dataDir+'WJetsToLNu_Pt-600ToInf.root',],
        #               },
        'GJets_100To200': { 'label':'#gamma + jets',
                            'datacard': 'gjets',
                            'color' : "#db4dff", # "#9A9EAB", #colors.keys()[1],
                            'ordering': 1,
                            'xsec' : 9235.0,
                            'files':[dataDir+'GJets_HT-100To200.root'],
                            },
        'GJets_200To400': { 'label':'#gamma + jets',
                            'datacard': 'gjets',
                            'color' : "#db4dff", # "#9A9EAB", #colors.keys()[1],
                            'ordering': 1,
                            'xsec' : 2298.0,
                            'files':[dataDir+'GJets_HT-200To400.root'],
                           },
        'GJets_400To600': { 'label':'#gamma + jets',
                            'datacard': 'gjets',
                            'color' : "#db4dff", # "#9A9EAB", #colors.keys()[1],
                            'ordering': 1,
                            'xsec' : 277.6,
                            'files':[dataDir+'GJets_HT-400To600.root'],
                            },
        'GJets_600ToInf': { 'label':'#gamma + jets',
                            'datacard': 'gjets',
                            'color' : "#db4dff", # "#9A9EAB", #colors.keys()[1],
                            'ordering': 1,
                            'xsec' : 93.47,
                            'files':[dataDir+'GJets_HT-600ToInf.root'],
                            },
        'ttbar': { 'label':'Top quark',
                    'datacard':'others',
                    'color' : "#CF3721", #colors.keys()[3],
                    'ordering': 2,
                    'xsec' : 831.76,
                   'files':[dataDir+'TT.root',],
                   #'files':['/afs/cern.ch/work/z/zdemirag/public/ichep/setup80x/Skim_v6/monojet_TT.root'],
                   },        
        'antitop': { 'label':'Top quark',
                    'datacard':'others',
                    'color' : "#CF3721", #colors.keys()[3],
                    'ordering': 2,
                    'xsec' : 26.22,
                    'files' : [dataDir+'ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8.root'],
                    },
        'top': { 'label':'Top quark',
                    'datacard':'others',
                    'color' : "#CF3721",# colors.keys()[3],
                    'ordering': 2,
                    'xsec' : 44.07,
                    'files':[dataDir+'ST_t-channel_top_4f_leptonDecays_13TeV-powheg-pythia8.root'],
                 },
        'antitop_5f': { 'label':'Top quark',
                    'datacard':'others',
                    'color' : "#CF3721", #colors.keys()[3],
                    'ordering': 2,
                    'xsec' : 35.6,
                    'files':[dataDir+'ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8.root'],
                    },
        'top_5f': { 'label':'Top quark',
                    'datacard':'others',
                    'color' : "#CF3721", #colors.keys()[3],
                    'ordering': 2,
                    'xsec' : 35.6,
                    'files' :[dataDir+'ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8.root']
                    },
        'WW' : { 'label':'Diboson',
                 'datacard':'others',
                 'color':"#4897D8", #colors.keys()[0],
                 'ordering': 2,
                 'xsec' : 118.7,
                 'files':[dataDir+'WW.root',],
                 },
        'ZZ' : { 'label':'Diboson',
                 'datacard':'others',
                 'color':"#4897D8", #colors.keys()[0],
                 'ordering': 2,
                 'xsec' : 16.6,
                 'files':[dataDir+'ZZ.root',],
                 },
        'WZ' : { 'label':'Diboson',
                 'datacard':'others',
                 'color':"#4897D8", #colors.keys()[0],
                 'ordering': 2,
                 'xsec' : 47.2,
                 'files':[dataDir+'WZ.root',],
                 },

        'EWKZ2Jets_ZToNuNu' : { 'label':'EWK W/Z + 2jets',
                'datacard':'ewk_z',
                'color':"#000000",#colors.keys()[8],
                'ordering': 3,
                'xsec' : 10.04,
                'files':[dataDir+'EWKZ2Jets_ZToNuNu_13TeV.root',],
                },       

        'EWKZ2Jets_ZToLL' : { 'label':'EWK W/Z + 2jets',
                'datacard':'ewk_z',
                'color':"#000000",#colors.keys()[8],
                'ordering': 3,
                'xsec' : 3.99,
                'files':[dataDir+'EWKZ2Jets_ZToLL_M-50_13TeV.root',],
                },       

        'EWKWPlus' : { 'label':'EWK W/Z + 2jets',
                'datacard':'ewk_w',
                'color':"#000000",#colors.keys()[8],
                'ordering': 3,
                'xsec' : 25.81,
                'files':[dataDir+'EWKWPlus2Jets_WToLNu_M-50_13TeV.root',],
                },       

        'EWKWMinus' : { 'label':'EWK W/Z + 2jets',
                'datacard':'ewk_w',
                'color':"#000000",#colors.keys()[8],
                'ordering': 3,
                'xsec' : 20.35,
                'files':[dataDir+'EWKWMinus2Jets_WToLNu_M-50_13TeV.root',],
                },       
        'QCD_200To300': { 'label':'QCD',
                          'datacard':'qcd',
                          'color' : "#F1F1F2" , #colors.keys()[2],
                          'ordering': 2,
                          'xsec' : 1735000.0*2,
                          'files':[dataDir+'QCD_HT200to300.root'],
                          },
        'QCD_300To500': { 'label':'QCD',
                          'datacard':'qcd',
                          'color' : "#F1F1F2" , #colors.keys()[2],
                          'ordering': 2,
                          'xsec' : 366800.0*2,
                          'files':[dataDir+'QCD_HT300to500.root'],
                          },
        'QCD_500To700': { 'label':'QCD',
                          'datacard':'qcd',
                          'color' : "#F1F1F2" , #colors.keys()[2],
                          'ordering': 2,
                          'xsec' : 29370.0*2,
                          'files':[dataDir+'QCD_HT500to700.root'],
                          },
        'QCD_700To1000': { 'label':'QCD',
                           'datacard':'qcd',
                           'color' : "#F1F1F2" , #colors.keys()[2],
                           'ordering': 2,
                           'xsec' : 6524.0*2,
                           'files':[dataDir+'QCD_HT700to1000.root'],
                           },
        'QCD_1000To1500': { 'label':'QCD',
                            'datacard':'qcd',
                            'color' :"#F1F1F2", # colors.keys()[2],
                            'ordering': 2,
                            'xsec' : 1064.0*2,
                            'files':[dataDir+'QCD_HT1000to1500.root'],
                            },
        'QCD_1500To2000': { 'label':'QCD',
                            'datacard':'qcd',
                            'color' :"#F1F1F2", # colors.keys()[2],
                            'ordering': 2,
                            'xsec' : 121.5*2,
                            'files':[dataDir+'QCD_HT1500to2000.root'],
                            },

        'QCD_2000ToInf': { 'label':'QCD',
                            'datacard':'qcd',
                            'color' :"#F1F1F2", # colors.keys()[2],
                            'ordering': 2,
                            'xsec' : 25.42*2,
                            'files':[dataDir+'QCD_HT2000toInf.root'],
                            },

        'data': { 'label':'Data',
                  'datacard':'data',
                  'color': 1,
                  'ordering': 6,    
                  'xsec' : 1.0,                  
                  #'files':[dataDir+'MET.root',],                  
                  'files':['/afs/cern.ch/work/z/zdemirag/public/ichep/setup80x/Skim_v15/monojet_MET.root',],                  
                  },
        'signal_vbf': {'label':'qqH 125',
                       'datacard':'signal',
                       'color':1,
                       'ordering': 7,
                       'xsec' : 10.0,
                       'files':[dataDir+'VBF_HToInvisible_M125_13TeV_powheg_pythia8.root',],
                       },
        
#        'signal_ggf': {'label':'ggH 125',
#                       'datacard':'signal',
#                       'color':1,
#                       'ordering': 7,
#                       'xsec' : 43.92,
#                       #'xsec' : 0.0,
#                       'files':[dataDir+'GluGlu_HToInvisible_M125_13TeV_powheg_pythia8.root',],                
#                   }
        
        }

tmp = {}
for p in physics_processes: 
	if physics_processes[p]['ordering']>-1: tmp[p] = physics_processes[p]['ordering']
ordered_physics_processes = []

for key, value in sorted(tmp.iteritems(), key=lambda (k,v): (v,k)):
	ordered_physics_processes.append(key)

def makeTrees(process,tree,channel):
	Trees={}
	Trees[process]   = TChain(tree)
	for sample in  physics_processes[process]['files']:
		Trees[process].Add(sample)
                #Trees[process].AddFriend("corrections",sample)
	return Trees[process]

######################################################
