#! /usr/bin/env python

from ROOT import *
from colors import *
colors = defineColors()

lumi = 1.0

######################################################

dataDir = "/afs/cern.ch/work/z/zdemirag/public/ichep/SkimOut/monojet_"

physics_processes = {
        'Zll_ht100': { 'label':'Z#rightarrow ll',
                       'datacard':'Zll',
                       'color' : colors.keys()[0],
                       'ordering': 0,                  
                       'xsec' : 148.0,
                       'files':[dataDir+"DYJetsToLL_M-50_HT-100to200.root"],
                 },
        'Zll_ht200': { 'label':'Z#rightarrow ll',
                       'datacard':'Zll',
                       'color' : colors.keys()[0],
                       'ordering': 0,                  
                       'xsec' : 40.94,
                       'files':[dataDir+"DYJetsToLL_M-50_HT-200to400.root"],
                       },
        'Zll_ht400': { 'label':'Z#rightarrow ll',
                       'datacard':'Zll',
                       'color' : colors.keys()[0],
                       'ordering': 0,                  
                       'xsec' : 5.497,
                       'files':[dataDir+"DYJetsToLL_M-50_HT-400to600.root"],
                 },        
        'Zll_ht600': { 'label':'Z#rightarrow ll',
                       'datacard':'Zll',
                       'color' : colors.keys()[0],
                       'ordering': 0,
                       'xsec' : 2.193,
                       'files':[dataDir+"DYJetsToLL_M-50_HT-600toInf.root"],
                 },
        'Wlv_ht100': { 'label':'W#rightarrow  l#nu',
                       'datacard':'Wlv',
                       'color' : colors.keys()[2],
                       'ordering': 3,                  
                       'xsec' : 1343.,
                       'files':[dataDir+'WJetsToLNu_HT-100To200.root',],
                       },
        'Wlv_ht200': { 'label':'W#rightarrow  l#nu',
                       'datacard':'Wlv',
                       'color' : colors.keys()[2],
                       'ordering': 3,                  
                       'xsec' : 359.6,
                       'files':[dataDir+'WJetsToLNu_HT-200To400.root',],
                       },
        'Wlv_ht400': { 'label':'W#rightarrow  l#nu',
                       'datacard':'Wlv',
                       'color' : colors.keys()[2],
                       'ordering': 3,                  
                       'xsec' : 48.85,
                       'files':[dataDir+'WJetsToLNu_HT-400To600.root',],
                       },
        'Wlv_ht600': { 'label':'W#rightarrow  l#nu',
                       'datacard':'Wlv',
                       'color' : colors.keys()[2],
                       'ordering': 3,
                       'xsec' : 12.05,
                       'files':[dataDir+'WJetsToLNu_HT-600To800.root',],
                       },
        'Wlv_ht800': { 'label':'W#rightarrow  l#nu',
                       'datacard':'Wlv',
                       'color' : colors.keys()[2],
                       'ordering': 3,
                       'xsec' : 5.5,
                       'files':[dataDir+'WJetsToLNu_HT-800To1200.root',],
                       },
        'Wlv_ht1200': { 'label':'W#rightarrow  l#nu',
                       'datacard':'Wlv',
                       'color' : colors.keys()[2],
                       'ordering': 3,
                       'xsec' : 1.32,
                       'files':[dataDir+'WJetsToLNu_HT-1200To2500.root',],
                       },
        'Wlv_ht2500': { 'label':'W#rightarrow  l#nu',
                       'datacard':'Wlv',
                       'color' : colors.keys()[2],
                       'ordering': 3,
                       'xsec' : 0.032,
                       'files':[dataDir+'WJetsToLNu_HT-2500ToInf.root',],
                       },

        'QCD_200To300': { 'label':'QCD',
                          'datacard':'qcd',
                          'color' : colors.keys()[1],
                          'ordering': 2,
                          'xsec' : 1735000.0,
                          'files':[dataDir+'QCD_HT200to300.root'],
                          },
        'QCD_300To500': { 'label':'QCD',
                          'datacard':'qcd',
                          'color' : colors.keys()[1],
                          'ordering': 2,
                          'xsec' : 366800.0,
                          'files':[dataDir+'QCD_HT300to500.root'],
                          },
        'QCD_500To700': { 'label':'QCD',
                          'datacard':'qcd',
                          'color' : colors.keys()[1],
                          'ordering': 2,
                          'xsec' : 29370.0,
                          'files':[dataDir+'QCD_HT500to700.root'],
                          },
        'QCD_700To1000': { 'label':'QCD',
                           'datacard':'qcd',
                           'color' : colors.keys()[1],
                           'ordering': 2,
                           'xsec' : 6524.0,
                           'files':[dataDir+'QCD_HT700to1000.root'],
                           },
        'QCD_1000To1500': { 'label':'QCD',
                            'datacard':'qcd',
                            'color' : colors.keys()[1],
                            'ordering': 2,
                            'xsec' : 1064.0,
                            'files':[dataDir+'QCD_HT1000to1500.root'],
                            },

        'ttbar': { 'label':'Top quark + diboson',
                    'datacard':'others',
                    'color' : colors.keys()[3],
                    'ordering': 2,
                    'xsec' : 831.76,
                    'files':[dataDir+'TTJets.root',],
                    },        
        'antitop': { 'label':'Top quark + diboson',
                    'datacard':'others',
                    'color' : colors.keys()[3],
                    'ordering': 2,
                    'xsec' : 26.22,
                    'files':[dataDir+'ST_t-channel_antitop_4f_leptonDecays_13TeV-powheg-pythia8.root',],
                    },
        'top': { 'label':'Top quark + diboson',
                    'datacard':'others',
                    'color' : colors.keys()[3],
                    'ordering': 2,
                    'xsec' : 44.07,
                    'files':[dataDir+'ST_t-channel_top_4f_leptonDecays_13TeV-powheg-pythia8.root'],
                    },
        'antitop_5f': { 'label':'Top quark + diboson',
                    'datacard':'others',
                    'color' : colors.keys()[3],
                    'ordering': 2,
                    'xsec' : 35.6,
                    'files':[dataDir+'ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8.root'],
                    },
        'top_5f': { 'label':'Top quark + diboson',
                    'datacard':'others',
                    'color' : colors.keys()[3],
                    'ordering': 2,
                    'xsec' : 35.6,
                    'files':[dataDir+'ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8.root'],
                    },
        'WW' : { 'label':'Top quark + diboson',
                 'datacard':'others',
                 'color':colors.keys()[3],
                 'ordering': 2,
                 'xsec' : 118.7,
                 'files':[dataDir+'WW.root',],
                 },
        'ZZ' : { 'label':'Top quark + diboson',
                 'datacard':'others',
                 'color':colors.keys()[3],
                 'ordering': 2,
                 'xsec' : 16.6,
                 'files':[dataDir+'ZZ.root',],
                 },
        'WZ' : { 'label':'Top quark + diboson',
                 'datacard':'others',
                 'color':colors.keys()[3],
                 'ordering': 2,
                 'xsec' : 47.2,
                 'files':[dataDir+'WZ.root',],
                 },

        'data': { 'label':'Data',
                  'datacard':'data',
                  'color': 1,
                  'ordering': 6,    
                  'xsec' : 1.0,
                  'files':[dataDir+'SingleElectron.root',],
                  },

        'signal': {'label':'signal',
                   'datacard':'signal',
                   'color':1,
                   'ordering': 7,
                   'xsec' : 0.00001,
                   'files':[dataDir+'WZ.root',],
                   }       
        }

tmp = {}
for p in physics_processes: 
	if physics_processes[p]['ordering']>-1: tmp[p] = physics_processes[p]['ordering']
ordered_physics_processes = []

for key, value in sorted(tmp.iteritems(), key=lambda (k,v): (v,k)):
	ordered_physics_processes.append(key)

def makeTrees(process,tree,channel):
	Trees={}
	Trees[process] = TChain(tree)
	for sample in  physics_processes[process]['files']:
		Trees[process].Add(sample)
	return Trees[process]

######################################################
